//十人成绩
zhangsan.grade<-c(90,99,100)
zhangsan.grade
names(zhangsan.grade)<-c('C','JAVA','C#')
zhangsan.grade
lisi.grade<-c(92,98,90)
kecheng<-c('C','JAVA','C#')
names(lisi.grade)<-kecheng
lisi.grade
wangwu.grade<-c(97,100,53)
names(wangwu.grade)<-kecheng
wangwu.grade
xiao1.grade<-c(97,77,92)
names(xiao1.grade)<-kecheng
xiao1.grade
xiao2.grade<-c(90,57,99)
names(xiao2.grade)<-kecheng
xiao2.grade
xiao3.grade<-c(98,27,90)
names(xiao3.grade)<-kecheng
xiao3.grade
xiao4.grade<-c(96,72,94)
names(xiao4.grade)<-kecheng
xiao4.grade
xiao5.grade<-c(95,76,97)
names(xiao5.grade)<-kecheng
xiao5.grade
xiao6.grade<-c(93,74,92)
names(xiao6.grade)<-kecheng
xiao6.grade
xiao7.grade<-c(92,73,91)
names(xiao7.grade)<-kecheng
xiao7.grade
//将十人成绩合并为向量
grade<-rbind(zhangsan.grade,lisi.grade,wangwu.grade,xiao1.grade,xiao2.grade,xiao3.grade,xiao4.grade,xiao5.grade,xiao6.grade,xiao7.grade)
grade
//学号+姓名
number<-c('01','02','03','04','05','06','07','08','09','10')
number
name<-c('zhangsan','lisi','wangwu','xiao1','xiao2','xiao3','xiao4','xiao5','xiao6','xiao7')
name
//合并姓名+成绩
students<-list(number,name,grade)
students
names(students)<-c('number','name','grade')
students
//合并框架
student<-data.frame(students)
student
//添加一列
student$weight<-c(50,51,52,53,54,55,56,57,58,59)
student
//获取表头和某一行
student[3,]
//获取一列
student[,3]
//获取表头和某一列
student[1]
student[3,3]

//取出王五成绩，计算绩点1
Score<-function(wangwu.grade){
	if(wangwu.grade<75){
		return(1)
	}else 
		return(2)
}
//简化2
Score<-function(wangwu.grade){
	wangwu.grade<-ifelse((wangwu.grade<75),1,2)
	return(wangwu.grade)
}
wangwu.grade<-student[3,3]
Score(wangwu.grade)
wangwu.grade<-student[3,4]
Score(wangwu.grade)
wangwu.grade<-student[3,5]
Score(wangwu.grade)
